### ISSUE TITLE
Issue to install requirements 

### ISSUE THREAD

**Issue by Kysp74** [williamjacksn/pblive#22]
Hello
when do pip install -r requirements.txt

 i have an error , can't find eventlet on alpine-wheels git

Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://alpine-wheels.github.io/index/eventlet/

thx

**Comment by williamjacksn** [comment]
The `eventlet` package is [on PyPI](https://pypi.org/project/eventlet/), and pip should not have problems pulling it unless you have some special configuration.

**Comment by Kysp74** [comment]
It's ok, i manualy install eventlet 
pip don't find it on https://pypi.org/simple
