### ISSUE TITLE
Works fine locally, stuck saying please wait loading when reverse proxied.

### ISSUE THREAD

**Issue by DistractedCanuck** [williamjacksn/pblive#42]
Hi! First of all thank you for setting this up in docker. Does almost everything I need! 

I'm trying to serve this publicly behind a reverse proxy.  I can navigate to the page and choose a quiz.  But instead of giving me the colour selection screen it just gives me a please wait loading message. 

Any ideas? Thanks!

**Comment by Cptn727** [comment]
I had the same experience behind an nginx proxy.

**Comment by williamjacksn** [comment]
Perhaps this has something to do with the websocket endpoints not being proxied correctly?

https://flask-socketio.readthedocs.io/en/latest/deployment.html#using-nginx-as-a-websocket-reverse-proxy

**Comment by RajaRuling** [comment]
Below 3 changes will help to fix the issue (no nginx additional changes needed)
1)  pblive/pblive/templates/session.html  (wss) => var socket = io.connect('wss://' + document.domain + ':' + location.port);
2)  pblive/pblive/templates/admin_session.html (wss) => var socket = io.connect('wss://' + document.domain + ':' + location.port);
3)  pblive/pblive/__main__.py (cors) => socketio = flask_socketio.SocketIO(app, cors_allowed_origins="https://xyz.com:8081")
